# Description: Configuration file for the Regularised Evolution strategy on the MultNIST dataset.
seed: 1

futures_timeout: 300

dataset: "multnist"
load_in_gpu: True
num_classes: 10
channels: 3
image_size:
  - 28
  - 28
input_mode: "im"
train_mode:
  - "trainval"
  - "test"
  
score: "xe"
epochs: 64
patience: 64
test_epochs: 64
batch_size: 256
hpo_runs: 1
lr: 0.04
momentum: 0.9
weight_decay: 0.0003

search_space_computation_module_prob: 0.32
search_space_min_module_depth: 0
search_space_max_module_depth: 100
search_space_num_repeated_cells: 1

search_strategy: "re"
search_strategy_num_samples: 1000
search_strategy_init_pop_size: 1000
search_strategy_sample_size: 10
search_strategy_architecture_seed: warmup_synflow
search_strategy_continue_search: True
search_strategy_warmup_samples: 100

log: False
