# Description: Configuration file for the Regularised Evolution strategy on the AddNIST dataset.
seed: 0

dataset: "psicov"
load_in_gpu: False
num_classes:
  - 128
  - 128
channels: 57
image_size:
  - 128
  - 128
input_mode: "im"

score: "mae8"
epochs: 25
patience: 25
test_epochs: 200
batch_size: 8
hpo_runs: 1
lr: 0.001
momentum: 0.9
weight_decay: 0.0005

search_space_computation_module_prob: 0.32
search_space_min_module_depth: 0
search_space_max_module_depth: 100
search_space_num_repeated_cells: 1

search_strategy: "re"
search_strategy_num_samples: 1000
search_strategy_init_pop_size: 100
search_strategy_sample_size: 10
search_strategy_architecture_seed: "wideresnet16_4"
search_strategy_continue_search: True

log: False